// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TEST_TESTFLAT_H_
#define FLATBUFFERS_GENERATED_TEST_TESTFLAT_H_

#include "flatbuffers/flatbuffers.h"

namespace TestFlat {

struct KV;

struct TestObj;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) KV FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t key_;
  double value_;

 public:
  KV() {
    memset(static_cast<void *>(this), 0, sizeof(KV));
  }
  KV(uint64_t _key, double _value)
      : key_(flatbuffers::EndianScalar(_key)),
        value_(flatbuffers::EndianScalar(_value)) {
  }
  uint64_t key() const {
    return flatbuffers::EndianScalar(key_);
  }
  double value() const {
    return flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(KV, 16);

struct TestObj FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PICTURE_PATH = 6,
    VT_PICTURE_SIZE = 8,
    VT_FLAG = 10,
    VT_LIST = 12,
    VT_KV = 14
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const flatbuffers::String *picture_path() const {
    return GetPointer<const flatbuffers::String *>(VT_PICTURE_PATH);
  }
  uint32_t picture_size() const {
    return GetField<uint32_t>(VT_PICTURE_SIZE, 0);
  }
  uint8_t flag() const {
    return GetField<uint8_t>(VT_FLAG, 0);
  }
  const flatbuffers::Vector<uint64_t> *list() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_LIST);
  }
  const KV *kv() const {
    return GetStruct<const KV *>(VT_KV);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_PICTURE_PATH) &&
           verifier.VerifyString(picture_path()) &&
           VerifyField<uint32_t>(verifier, VT_PICTURE_SIZE) &&
           VerifyField<uint8_t>(verifier, VT_FLAG) &&
           VerifyOffset(verifier, VT_LIST) &&
           verifier.VerifyVector(list()) &&
           VerifyField<KV>(verifier, VT_KV) &&
           verifier.EndTable();
  }
};

struct TestObjBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(TestObj::VT_ID, id, 0);
  }
  void add_picture_path(flatbuffers::Offset<flatbuffers::String> picture_path) {
    fbb_.AddOffset(TestObj::VT_PICTURE_PATH, picture_path);
  }
  void add_picture_size(uint32_t picture_size) {
    fbb_.AddElement<uint32_t>(TestObj::VT_PICTURE_SIZE, picture_size, 0);
  }
  void add_flag(uint8_t flag) {
    fbb_.AddElement<uint8_t>(TestObj::VT_FLAG, flag, 0);
  }
  void add_list(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> list) {
    fbb_.AddOffset(TestObj::VT_LIST, list);
  }
  void add_kv(const KV *kv) {
    fbb_.AddStruct(TestObj::VT_KV, kv);
  }
  explicit TestObjBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TestObjBuilder &operator=(const TestObjBuilder &);
  flatbuffers::Offset<TestObj> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TestObj>(end);
    return o;
  }
};

inline flatbuffers::Offset<TestObj> CreateTestObj(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    flatbuffers::Offset<flatbuffers::String> picture_path = 0,
    uint32_t picture_size = 0,
    uint8_t flag = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> list = 0,
    const KV *kv = 0) {
  TestObjBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_kv(kv);
  builder_.add_list(list);
  builder_.add_picture_size(picture_size);
  builder_.add_picture_path(picture_path);
  builder_.add_flag(flag);
  return builder_.Finish();
}

inline flatbuffers::Offset<TestObj> CreateTestObjDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *picture_path = nullptr,
    uint32_t picture_size = 0,
    uint8_t flag = 0,
    const std::vector<uint64_t> *list = nullptr,
    const KV *kv = 0) {
  auto picture_path__ = picture_path ? _fbb.CreateString(picture_path) : 0;
  auto list__ = list ? _fbb.CreateVector<uint64_t>(*list) : 0;
  return TestFlat::CreateTestObj(
      _fbb,
      id,
      picture_path__,
      picture_size,
      flag,
      list__,
      kv);
}

inline const TestFlat::TestObj *GetTestObj(const void *buf) {
  return flatbuffers::GetRoot<TestFlat::TestObj>(buf);
}

inline const TestFlat::TestObj *GetSizePrefixedTestObj(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<TestFlat::TestObj>(buf);
}

inline bool VerifyTestObjBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<TestFlat::TestObj>(nullptr);
}

inline bool VerifySizePrefixedTestObjBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<TestFlat::TestObj>(nullptr);
}

inline void FinishTestObjBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<TestFlat::TestObj> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTestObjBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<TestFlat::TestObj> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace TestFlat

#endif  // FLATBUFFERS_GENERATED_TEST_TESTFLAT_H_
